### model
model_name_or_path: Qwen/Qwen2-VL-7B-Instruct

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all

### dataset
dataset: mire_train  # video: mllm_video_demo
template: qwen2_vl
cutoff_len: 1500
max_samples: 10000
overwrite_cache: true
preprocessing_num_workers: 16
val_size: 0.1

### output
output_dir: saves/Qwen2-VL-7B-Instruct/lora/train
logging_steps: 10
save_steps: 100
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 2
learning_rate: 2.0e-5
num_train_epochs: 5.0
lr_scheduler_type: cosine
warmup_ratio: 0.05
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 100

flash_attn: fa2